config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events
  resources :kids

  #root to: 'pages#home'
  root to: 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :kid
  belongs_to :user

  validates :title, presence: true
  validates :date, presence: true
  validates :place, presence: true
  validates :description, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/kid.rb
class Kid < ApplicationRecord
  has_many :users, through: :events
  has_many :events

  validates :name, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :kids, through: :events

  validates :first_name, presence: true
  validates :role, presence: true
  validates :email, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :role])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:log_in, keys: [:first_name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @all_kids = Kid.all
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user

    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @event = Event.new
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :date, :place, :photo, :description, :kid_id, :user_id)
  end
end

app/controllers/fams_controller.rb
class FamsController < ApplicationController
  def new
    @fam = Family.new
    @fam.users.build
  end

  def create
    @fam = Fam.new(fam_params)
    @fam.save
  end

  private

  def fam_params
    params.require(:fam).permit(:family_name)
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController

  def new
    @kid = Kid.new
  end

  def create
    @kid = Kid.new(kid_params)
    if @kid.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def kid_params
    params.require(:kid).permit(:name, :photo, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @events = Event.all.order(date: :desc)

    @latest_events = Event.all.order(date: :desc).limit(5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<div class="wrapper">
  <div class="tabs-games">
    <!-- Tab links -->
    <div class="tabs-underlined">
      <button class="tablinks" onclick="openTabs(event, 'list')"><h4>LIST</h4></button>
      <button class="tablinks" onclick="openTabs(event, 'map')"><h4>PLACES</h4></button>
    </div>
  </div>
  <!-- Tab content -->
  <div id="list" class="tabcontent">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <% @events.each do |event| %>
            <div class="event-card">
              <img src="<%= event.photo  %>"/>
              <div class="event-texts">
                <div class="event-title-date">
                  <h2><%= event.title %></h2>
                  <h5><%= event.date.strftime("%d.%m.%Y") %></h5>
                </div>
                <div class="event-description">
                  <h4> <%= event.description %> </h4>
                </div>
                <%= link_to "show memory", event_path(event) %>
                <div class="divider">
                  <%= image_tag "grenze.png" %>
                </div>
              </div>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
  <div id="map" class="tabcontent">
    Hier kommt bald eine Karte
  </div>
</div>

app/views/events/new.html.erb
<div class="wrapper">
  <div class="container-form">
    <div class="row-form">
      <div class="col-12">
        <h1>Create a new memory</h1>

        <%= simple_form_for(@event) do |f| %>
        <%= f.error :base %>
        <%= f.input :title %>
        <%= f.date_field :date %>
        <%= f.input :place %>
        <%= f.input :description %>
        <%= f.input :kid_id, :collection => @all_kids %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit %>
        <% end %>

      </div>

    </div>

  </div>

</div>

app/views/events/show.html.erb
<h2></h2>

app/views/fams/create.html.erb
<h1>Fams#create</h1>
<p>Find me in app/views/fams/create.html.erb</p>

app/views/fams/new.html.erb
<h1>Fams#new</h1>
<p>Find me in app/views/fams/new.html.erb</p>

app/views/kids/new.html.erb
<h2>Add your kid</h2>

<%= simple_form_for(@kid) do |f| %>
<%= f.input :name %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="event-wrapper">
  <div class="event-container">
    <div class="event-row">
      <div class="col-12">
        <div class="first-event">
          <div class="first-event-left">
            <h4><%= @latest_events.first.date.strftime("%d.%m.%Y") %></h4>
          </div>
          <div class="first-event-right">
            <h1><%= @latest_events.first.title %> </h1>
          </div>
          <img src="<%= @latest_events.first.photo %>">
        </div>
      </div>
    </div>
  </div>

<div class="event-second-container">
  <div class="event-second-row">
    <div class="col-5">
      <div class="second-event">
        <div class="second-event-center">
          <h1><%= @latest_events.second.kid.name %></h1>
        </div>
        <div  class="ratio img-circle" style="background-image: url(<%= @latest_events.second.photo %>);">
        </div>
      <div class="second-event-date">
        <h4><%= @latest_events.first.date.strftime("%d.%m.%Y") %></h4>
      </div>
        <span class="triangle up border"></span>
      </div>
    </div>
  </div>
</div>

<div class="event-third-container">
  <div class="event-third-row">
    <div class="col-6">
      <div class="third-event">

      </div>
    </div>
  </div>
</div>


<!--
<div class="event-container">
  <div class="event-row">
    <div class="col-xs-12">

        <%= @latest_events.second.title %>

    </div>
  </div>
</div>

<div class="event-container">
  <div class="event-row">
    <div class="col-xs-12">

        <%= @latest_events.third.title %>

    </div>
  </div>
</div>

<div class="event-container">
  <div class="event-row">
    <div class="col-xs-12">

        <%= @latest_events.fourth.title %>

    </div>
  </div>
</div>

<div class="event-container">
  <div class="event-row">
    <div class="col-xs-12">

        <%= @latest_events.fifth.title %>

    </div>
  </div>
</div> -->
<!-- delete if statement as soon as user has the option to add kids -->
<% if false %>
<%= link_to "+ add kid", new_kid_path %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-pepe">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <%= image_tag "burger_menue.png" %>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Memories", events_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Memories", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

</div>

<div class="add-event">
  <%= link_to image_tag('new_event.png'), new_event_path %>
</div>